SET SCHEMA "LEARNING_TO_NOTE";

DROP TABLE "PAIRS";
DROP TABLE "DOC_ENTITIES";
DROP TABLE "ENTITIES";
DROP TABLE "DOCUMENTS";


CREATE COLUMN TABLE "DOCUMENTS" (
                "ID" VARCHAR(255) PRIMARY KEY,
                "TEXT" NCLOB
              );

CREATE COLUMN TABLE "ENTITIES" (
                "ID" VARCHAR(255) PRIMARY KEY,
                "TYPE" VARCHAR(255),
                "TEXT" VARCHAR(255)
              );

CREATE COLUMN TABLE "DOC_ENTITIES" (
                "ID" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                "DOC_ID" VARCHAR(255),
                "ENTITY_ID" VARCHAR(255),
                "START" INT,
                "END" INT,
                FOREIGN KEY("DOC_ID") REFERENCES "DOCUMENTS" ON UPDATE CASCADE,
                FOREIGN KEY("ENTITY_ID") REFERENCES "ENTITIES" ON UPDATE CASCADE
              );

CREATE COLUMN TABLE "PAIRS" (
                "ID" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                "E1_ID" VARCHAR(255),
                "E2_ID" VARCHAR(255),
                "DDI" TINYINT,
                "TYPE" VARCHAR(255),
                FOREIGN KEY("E1_ID") REFERENCES "ENTITIES" ON UPDATE CASCADE,
                FOREIGN KEY("E2_ID") REFERENCES "ENTITIES" ON UPDATE CASCADE
              );
