DROP TABLE PAIR;
DROP TABLE ENTITY;
DROP TABLE SENTENCE;
DROP TABLE DOCUMENT;


CREATE TABLE DOCUMENT (ID VARCHAR(255) PRIMARY KEY);
CREATE TABLE SENTENCE (ID VARCHAR(255) PRIMARY KEY,
					   TEXT NCLOB,
					   DOCUMENT_ID VARCHAR(255),
					   FOREIGN KEY(DOCUMENT_ID) REFERENCES DOCUMENT ON UPDATE CASCADE);
CREATE TABLE ENTITY (ID VARCHAR(255) PRIMARY KEY,
					 CHAR_OFFSET_START INTEGER,
					 CHAR_OFFSET_END INTEGER,
					 TYPE VARCHAR(255),
					 TEXT VARCHAR(255),
					 SENTENCE_ID VARCHAR(255),
					 FOREIGN KEY(SENTENCE_ID) REFERENCES SENTENCE ON UPDATE CASCADE);
CREATE TABLE PAIR (ID VARCHAR(255) PRIMARY KEY,
	    		   E1_ID VARCHAR(255),
				   E2_ID VARCHAR(255),
				   DDI TINYINT,
				   FOREIGN KEY(E1_ID) REFERENCES ENTITY ON UPDATE CASCADE,
				   FOREIGN KEY(E2_ID) REFERENCES ENTITY ON UPDATE CASCADE);
				   


