DROP TABLE "PAIR";
DROP TABLE "OFFSET";
DROP TABLE "ENTITY";
DROP TABLE "SENTENCE";
DROP TABLE "DOCUMENT";


CREATE COLUMN TABLE "DOCUMENT" ("ID" VARCHAR(255) PRIMARY KEY);
CREATE COLUMN TABLE "SENTENCE" ("ID" VARCHAR(255) PRIMARY KEY,
								"TEXT" NCLOB,
								"DOCUMENT_ID" VARCHAR(255),
								FOREIGN KEY("DOCUMENT_ID") REFERENCES "DOCUMENT" ON UPDATE CASCADE);
CREATE COLUMN TABLE "ENTITY" ("ID" VARCHAR(255) PRIMARY KEY,
							  "TYPE" VARCHAR(255),
							  "TEXT" VARCHAR(255),
							  "SENTENCE_ID" VARCHAR(255),
							  FOREIGN KEY("SENTENCE_ID") REFERENCES "SENTENCE" ON UPDATE CASCADE);
CREATE COLUMN TABLE "OFFSET" ("ID" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
							  "START" INT,
							  "END" INT,
							  "ENTITY_ID" VARCHAR(255),
							  FOREIGN KEY("ENTITY_ID") REFERENCES "ENTITY" ON UPDATE CASCADE);					 
CREATE COLUMN TABLE "PAIR" ("ID" VARCHAR(255) PRIMARY KEY,
			    		    "E1_ID" VARCHAR(255),
						    "E2_ID" VARCHAR(255),
						    "DDI" TINYINT,
						    "TYPE" VARCHAR(255),
						    FOREIGN KEY("E1_ID") REFERENCES "ENTITY" ON UPDATE CASCADE,
						    FOREIGN KEY("E2_ID") REFERENCES "ENTITY" ON UPDATE CASCADE);
						    
