SET SCHEMA "LEARNING_TO_NOTE";

DROP TABLE "PAIRS";
DROP TABLE "OFFSETS";
DROP TABLE "ENTITIES";
DROP TABLE "DOCUMENTS";


CREATE COLUMN TABLE "DOCUMENTS" (
                "ID" VARCHAR(255) PRIMARY KEY,
                "TEXT" NCLOB
              );

CREATE COLUMN TABLE "ENTITIES" (
                "ID" VARCHAR(255) PRIMARY KEY,
                "DOC_ID" VARCHAR(255),
                "TYPE" VARCHAR(255),

                FOREIGN KEY("DOC_ID") REFERENCES "DOCUMENTS" ON DELETE CASCADE
              );

CREATE COLUMN TABLE "OFFSETS" (
                "START" INT,
                "END" INT,
                "ENTITY_ID" VARCHAR(255),

                FOREIGN KEY("ENTITY_ID") REFERENCES "ENTITIES" ON DELETE CASCADE
              );

CREATE COLUMN TABLE "PAIRS" (
                "ID" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                "E1_ID" VARCHAR(255),
                "E2_ID" VARCHAR(255),
                "DDI" TINYINT,
                "TYPE" VARCHAR(255),

                FOREIGN KEY("E1_ID") REFERENCES "ENTITIES" ON DELETE CASCADE,
                FOREIGN KEY("E2_ID") REFERENCES "ENTITIES" ON DELETE CASCADE
              );


DELETE FROM "PAIRS";
DELETE FROM "OFFSETS";
DELETE FROM "ENTITIES";
DELETE FROM "DOCUMENTS";
